name: Run Data Pipeline and Save to Output Branch

permissions:                # Job-level permissions configuration starts here
  contents: write           # 'write' access to repository contents
  pull-requests: write      # 'write' access to pull requests
  
on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 1 * *'

jobs:
  run-and-store:
    runs-on: ubuntu-latest
    
    env:
      DRIVE_SHARE_URL: ${{ secrets.DRIVE_SHARE_URL }}
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run pipeline shell script
        run: |
          chmod +x scripts/run-pipeline.sh
          ./scripts/run-pipeline.sh

      - name: Push to orphan branch
        run: |
          # Push the orphan branch (using authentication)
          git push -f origin data-output-temp:data-output 
